###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401,F821
# flake8: noqa: E501,F401,F821
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum
from pydantic import BaseModel, ConfigDict
from typing_extensions import TypeAlias
from typing import Dict, Generic, List, Literal, Optional, TypeVar, Union


T = TypeVar('T')
CheckName = TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str

class Checked(BaseModel, Generic[T,CheckName]):
    value: T
    checks: Dict[CheckName, Check]

def get_checks(checks: Dict[CheckName, Check]) -> List[Check]:
    return list(checks.values())

def all_succeeded(checks: Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))



class ContactMethod(str, Enum):
    
    Email = "Email"
    Phone = "Phone"

class Gender(str, Enum):
    
    Male = "Male"
    Female = "Female"
    Other = "Other"

class ContactInfo(BaseModel):
    email: str
    phone: Optional[str] = None
    preferred_contact_method: "ContactMethod"
    call_reasons: List[str]

class CustomerInformation(BaseModel):
    personal_info: "PersonalInfo"
    contact_info: "ContactInfo"

class PersonalInfo(BaseModel):
    first_name: str
    last_name: str
    gender: Optional["Gender"] = None

class Theme(BaseModel):
    title: str
    description: str

class ThemeClassification(BaseModel):
    model_reasoning: str
    chosen_theme: "Theme"
